/**
 * Documentation Generator
 * Generates comprehensive documentation for Backstage templates
 */

import {
  TemplateSpec,
  Documentation,
  CapabilityMaturity,
  DevelopmentPhase,
} from '../types/core';

export class DocumentationGenerator {
  /**
   * Generate comprehensive documentation for a template specification
   */
  async generateDocumentation(spec: TemplateSpec): Promise<Documentation> {
    const readme = await this.generateReadme(spec);
    const techDocs = await this.generateTechDocs(spec);
    const apiDocs = await this.generateApiDocs(spec);
    const usageExamples = await this.generateUsageExamples(spec);

    return {
      readme,
      techDocs,
      apiDocs,
      usageExamples,
    };
  }

  /**
   * Generate comprehensive README documentation
   */
  private async generateReadme(spec: TemplateSpec): Promise<string> {
    const templateName = spec.metadata.name;
    const description = spec.metadata.description;
    const tags = spec.metadata.tags;
    const owner = spec.metadata.owner;

    const parametersSection = this.generateParametersSection(spec);
    const stepsSection = this.generateStepsSection(spec);
    const validationSection = this.generateValidationSection(spec);
    const usageSection = this.generateUsageSection(spec);

    return `# ${this.formatTitle(templateName)}

${description}

## Overview

This Backstage template provides ${this.generateOverviewDescription(spec)}.

**Template Tags:** ${tags.map((tag) => `\`${tag}\``).join(', ')}  
**Owner:** ${owner}  
**Template Type:** ${this.detectTemplateType(spec)}

## Features

${this.generateFeaturesList(spec)}

## Prerequisites

${this.generatePrerequisites(spec)}

## Parameters

${parametersSection}

## Template Steps

${stepsSection}

## Usage

${usageSection}

## Validation Rules

${validationSection}

## Generated Structure

This template will generate the following structure:

\`\`\`
${this.generateStructurePreview(spec)}
\`\`\`

## Development Guidelines

${this.generateDevelopmentGuidelines(spec)}

## Troubleshooting

${this.generateTroubleshooting(spec)}

## Contributing

${this.generateContributingSection(spec)}

## Support

For questions or issues with this template, please:

1. Check the [troubleshooting section](#troubleshooting) above
2. Review the template documentation in Backstage
3. Contact the ${owner} team
4. Create an issue in the template repository

## License

This template is part of the organizational IDP and follows internal licensing policies.

---

*Generated by Backstage Template Generator*
`;
  }

  /**
   * Generate TechDocs documentation
   */
  private async generateTechDocs(spec: TemplateSpec): Promise<string> {
    const templateName = spec.metadata.name;
    const description = spec.metadata.description;

    return `# ${this.formatTitle(templateName)} - Technical Documentation

## Introduction

${description}

This document provides comprehensive technical documentation for the ${templateName} Backstage template, including architecture decisions, implementation details, and operational guidance.

## Architecture

### Template Architecture

${this.generateArchitectureSection(spec)}

### Component Overview

${this.generateComponentOverview(spec)}

## Implementation Details

### Template Configuration

The template is configured with the following key components:

${this.generateImplementationDetails(spec)}

### Parameter Schema

${this.generateParameterSchema(spec)}

### Step Implementation

${this.generateStepImplementation(spec)}

## Validation Framework

${this.generateValidationFramework(spec)}

## Security Considerations

${this.generateSecurityConsiderations(spec)}

## Performance Guidelines

${this.generatePerformanceGuidelines(spec)}

## Monitoring and Observability

${this.generateMonitoringSection(spec)}

## Deployment Strategy

${this.generateDeploymentStrategy(spec)}

## Maintenance and Updates

${this.generateMaintenanceSection(spec)}

## API Reference

${this.generateApiReference(spec)}

## Configuration Reference

${this.generateConfigurationReference(spec)}

## Troubleshooting Guide

${this.generateDetailedTroubleshooting(spec)}

## Change Log

${this.generateChangeLog(spec)}

---

*Last updated: ${new Date().toISOString()}*
*Generated by Backstage Template Generator*
`;
  }

  /**
   * Generate API documentation if applicable
   */
  private async generateApiDocs(
    spec: TemplateSpec
  ): Promise<string | undefined> {
    if (!this.isApiTemplate(spec)) {
      return undefined;
    }

    const templateName = spec.metadata.name;

    return `# ${this.formatTitle(templateName)} - API Documentation

## API Overview

This template generates a REST API service with the following characteristics:

${this.generateApiOverview(spec)}

## Endpoints

${this.generateEndpointsDocumentation(spec)}

## Authentication

${this.generateAuthenticationDocs(spec)}

## Request/Response Format

${this.generateRequestResponseDocs(spec)}

## Error Handling

${this.generateErrorHandlingDocs(spec)}

## Rate Limiting

${this.generateRateLimitingDocs(spec)}

## OpenAPI Specification

${this.generateOpenApiDocs(spec)}

## SDK and Client Libraries

${this.generateSdkDocs(spec)}

## Testing

${this.generateApiTestingDocs(spec)}

---

*Generated by Backstage Template Generator*
`;
  }

  /**
   * Generate usage examples
   */
  private async generateUsageExamples(spec: TemplateSpec): Promise<string[]> {
    const examples: string[] = [];

    // Basic usage example
    examples.push(this.generateBasicUsageExample(spec));

    // Advanced usage examples based on template type
    if (this.isApiTemplate(spec)) {
      examples.push(this.generateApiUsageExample(spec));
    }

    if (this.isDataTemplate(spec)) {
      examples.push(this.generateDataUsageExample(spec));
    }

    if (this.isContainerTemplate(spec)) {
      examples.push(this.generateContainerUsageExample(spec));
    }

    if (this.isCloudTemplate(spec)) {
      examples.push(this.generateCloudUsageExample(spec));
    }

    // Maturity-specific examples
    const maturityLevel = this.extractMaturityLevel(spec);
    if (
      maturityLevel === CapabilityMaturity.L4_GOVERNANCE ||
      maturityLevel === CapabilityMaturity.L5_INTENT_DRIVEN
    ) {
      examples.push(this.generateAdvancedUsageExample(spec));
    }

    return examples;
  }

  /**
   * Helper methods for generating documentation sections
   */
  private formatTitle(name: string): string {
    return name
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  private generateOverviewDescription(spec: TemplateSpec): string {
    const templateType = this.detectTemplateType(spec);
    const tags = spec.metadata.tags;

    if (tags.includes('api') || tags.includes('service')) {
      return 'a production-ready API service with comprehensive documentation, testing, and deployment automation';
    }
    if (tags.includes('frontend') || tags.includes('ui')) {
      return 'a modern frontend application with best practices for user interface development';
    }
    if (tags.includes('data') || tags.includes('pipeline')) {
      return 'a robust data processing pipeline with monitoring and error handling';
    }
    if (tags.includes('library') || tags.includes('package')) {
      return 'a reusable library package with comprehensive testing and documentation';
    }

    return `a ${templateType} solution following organizational best practices`;
  }

  private generateFeaturesList(spec: TemplateSpec): string {
    const features: string[] = [];
    const tags = spec.metadata.tags;

    // Core features
    features.push(
      '🏗️ **Automated Setup** - Complete project scaffolding with best practices'
    );
    features.push(
      '📚 **Comprehensive Documentation** - Auto-generated README, TechDocs, and API docs'
    );
    features.push(
      '🔒 **Security Baseline** - Built-in security controls and validation'
    );
    features.push(
      '🧪 **Testing Framework** - Unit tests, integration tests, and quality gates'
    );

    // Template-specific features
    if (tags.includes('api') || tags.includes('service')) {
      features.push(
        '🌐 **REST API** - OpenAPI specification and endpoint documentation'
      );
      features.push(
        '🔐 **Authentication** - JWT-based authentication and authorization'
      );
      features.push('📊 **Monitoring** - Health checks, metrics, and logging');
    }

    if (tags.includes('frontend') || tags.includes('ui')) {
      features.push(
        '⚛️ **Modern Framework** - React/Vue/Angular with TypeScript'
      );
      features.push(
        '🎨 **Design System** - Consistent UI components and styling'
      );
      features.push(
        '📱 **Responsive Design** - Mobile-first responsive layouts'
      );
    }

    if (tags.includes('data') || tags.includes('pipeline')) {
      features.push(
        '📊 **Data Processing** - ETL pipelines with error handling'
      );
      features.push(
        '🔄 **Scheduling** - Automated job scheduling and monitoring'
      );
      features.push('📈 **Analytics** - Data quality metrics and reporting');
    }

    if (tags.includes('docker') || tags.includes('container')) {
      features.push(
        '🐳 **Containerization** - Docker support with multi-stage builds'
      );
      features.push(
        '☸️ **Kubernetes** - Deployment manifests and configurations'
      );
    }

    if (tags.includes('cloud') || tags.includes('aws')) {
      features.push(
        '☁️ **Cloud Native** - Cloud provider integrations and services'
      );
      features.push('🚀 **Auto Scaling** - Automatic scaling based on demand');
      features.push(
        '💰 **Cost Optimization** - Resource tagging and cost controls'
      );
    }

    return features.join('\n');
  }

  private generatePrerequisites(spec: TemplateSpec): string {
    const prerequisites: string[] = [];
    const tags = spec.metadata.tags;

    // Common prerequisites
    prerequisites.push('- Access to Backstage instance');
    prerequisites.push('- Git repository access');
    prerequisites.push('- Appropriate permissions for resource creation');

    // Language-specific prerequisites
    if (tags.includes('typescript') || tags.includes('javascript')) {
      prerequisites.push('- Node.js 18+ and npm/yarn');
    }
    if (
      tags.includes('python') ||
      tags.includes('data') ||
      tags.includes('pipeline')
    ) {
      prerequisites.push('- Python 3.9+ and pip');
    }
    if (tags.includes('java')) {
      prerequisites.push('- Java 17+ and Maven/Gradle');
    }
    if (tags.includes('go')) {
      prerequisites.push('- Go 1.19+ and Go modules');
    }

    // Infrastructure prerequisites
    if (tags.includes('docker')) {
      prerequisites.push('- Docker and Docker Compose');
    }
    if (tags.includes('kubernetes')) {
      prerequisites.push('- Kubernetes cluster access');
      prerequisites.push('- kubectl configured');
    }
    if (tags.includes('aws')) {
      prerequisites.push('- AWS account and CLI configured');
      prerequisites.push('- Appropriate IAM permissions');
    }

    return prerequisites.join('\n');
  }

  private generateParametersSection(spec: TemplateSpec): string {
    if (!spec.parameters || Object.keys(spec.parameters).length === 0) {
      return 'This template uses default parameters. No additional configuration required.';
    }

    let section =
      'The following parameters can be configured when using this template:\n\n';

    // This would ideally parse the JSONSchema, but for now we'll provide a general structure
    section += '| Parameter | Type | Required | Description |\n';
    section += '|-----------|------|----------|-------------|\n';
    section += '| `name` | string | Yes | The name of the component |\n';
    section +=
      '| `description` | string | Yes | Description of the component |\n';
    section += '| `owner` | string | Yes | Team or individual responsible |\n';

    const tags = spec.metadata.tags;
    if (tags.includes('api')) {
      section += '| `port` | number | No | API server port (default: 3000) |\n';
      section +=
        '| `database` | boolean | No | Include database integration |\n';
    }

    if (tags.includes('frontend')) {
      section +=
        '| `framework` | string | No | Frontend framework (react/vue/angular) |\n';
      section +=
        '| `styling` | string | No | Styling approach (css/scss/styled-components) |\n';
    }

    return section;
  }

  private generateStepsSection(spec: TemplateSpec): string {
    if (!spec.steps || spec.steps.length === 0) {
      return 'This template follows the standard Backstage template workflow.';
    }

    let section = 'This template executes the following steps:\n\n';

    spec.steps.forEach((step, index) => {
      section += `${index + 1}. **${step.name}** - ${this.getStepDescription(
        step.action
      )}\n`;
    });

    return section;
  }

  private generateValidationSection(spec: TemplateSpec): string {
    const rules = spec.validation;
    if (
      !rules ||
      (rules.security.length === 0 &&
        rules.standards.length === 0 &&
        rules.compliance.length === 0)
    ) {
      return 'This template follows standard organizational validation rules.';
    }

    let section = 'This template enforces the following validation rules:\n\n';

    if (rules.security.length > 0) {
      section += '### Security Rules\n';
      rules.security.forEach((rule) => {
        const icon = rule.enforcement === 'block' ? '🚫' : '⚠️';
        section += `- ${icon} ${rule.rule}\n`;
      });
      section += '\n';
    }

    if (rules.compliance.length > 0) {
      section += '### Compliance Rules\n';
      rules.compliance.forEach((rule) => {
        const icon = rule.enforcement === 'block' ? '🚫' : '⚠️';
        section += `- ${icon} ${rule.rule}\n`;
      });
      section += '\n';
    }

    if (rules.standards.length > 0) {
      section += '### Code Standards\n';
      rules.standards.forEach((rule) => {
        const icon = rule.enforcement === 'block' ? '🚫' : '⚠️';
        section += `- ${icon} ${rule.rule}\n`;
      });
      section += '\n';
    }

    return section;
  }

  private generateUsageSection(spec: TemplateSpec): string {
    const templateName = spec.metadata.name;

    return `### Using this Template

1. **Navigate to Backstage** - Go to your Backstage instance
2. **Create Component** - Click "Create Component" or use the Software Catalog
3. **Select Template** - Choose "${templateName}" from the available templates
4. **Fill Parameters** - Provide the required information in the form
5. **Review & Create** - Review your configuration and create the component

### Command Line Usage

You can also use this template via the Backstage CLI:

\`\`\`bash
# Install Backstage CLI if not already installed
npm install -g @backstage/cli

# Create component from template
backstage-cli create --template ${templateName}
\`\`\`

### Programmatic Usage

For automated workflows, you can use the Backstage API:

\`\`\`bash
curl -X POST "https://your-backstage-instance/api/scaffolder/v2/tasks" \\
  -H "Content-Type: application/json" \\
  -d '{
    "templateRef": "${templateName}",
    "values": {
      "name": "my-component",
      "description": "My new component",
      "owner": "my-team"
    }
  }'
\`\`\`
`;
  }

  private generateBasicUsageExample(spec: TemplateSpec): string {
    const templateName = spec.metadata.name;

    return `## Basic Usage Example

This example shows how to create a basic component using the ${templateName} template:

\`\`\`yaml
# Template parameters
name: my-new-service
description: A new service for handling user data
owner: backend-team
tags:
  - service
  - api
  - backend

# Generated structure
my-new-service/
├── src/
│   ├── index.ts
│   ├── routes/
│   └── models/
├── tests/
├── docs/
├── Dockerfile
├── package.json
└── README.md
\`\`\`

The template will automatically:
- Set up the project structure
- Configure build and test scripts
- Generate documentation
- Apply security and validation rules
`;
  }

  private generateApiUsageExample(spec: TemplateSpec): string {
    return `## API Service Example

Creating a REST API service with authentication and database integration:

\`\`\`yaml
# Template parameters
name: user-management-api
description: REST API for user management
owner: backend-team
port: 3000
database: true
authentication: jwt

# Generated API structure
user-management-api/
├── src/
│   ├── controllers/
│   │   └── userController.ts
│   ├── models/
│   │   └── User.ts
│   ├── middleware/
│   │   └── auth.ts
│   ├── routes/
│   │   └── users.ts
│   └── app.ts
├── tests/
│   ├── unit/
│   └── integration/
├── docs/
│   └── api.md
└── openapi.yaml
\`\`\`

Generated endpoints:
- \`GET /api/users\` - List users
- \`POST /api/users\` - Create user
- \`GET /api/users/:id\` - Get user by ID
- \`PUT /api/users/:id\` - Update user
- \`DELETE /api/users/:id\` - Delete user
`;
  }

  private generateDataUsageExample(spec: TemplateSpec): string {
    return `## Data Pipeline Example

Creating a data processing pipeline with ETL capabilities:

\`\`\`yaml
# Template parameters
name: sales-data-pipeline
description: ETL pipeline for sales data processing
owner: data-team
schedule: "0 2 * * *"  # Daily at 2 AM
source: postgresql
destination: data-warehouse

# Generated pipeline structure
sales-data-pipeline/
├── src/
│   ├── extractors/
│   │   └── salesExtractor.py
│   ├── transformers/
│   │   └── salesTransformer.py
│   ├── loaders/
│   │   └── warehouseLoader.py
│   └── pipeline.py
├── config/
│   ├── dev.yaml
│   └── prod.yaml
├── tests/
└── monitoring/
    └── alerts.yaml
\`\`\`

Pipeline features:
- Automated data extraction from PostgreSQL
- Data validation and transformation
- Error handling and retry logic
- Monitoring and alerting
- Scheduled execution
`;
  }

  private generateContainerUsageExample(spec: TemplateSpec): string {
    return `## Containerized Application Example

Creating a containerized application with Kubernetes deployment:

\`\`\`yaml
# Template parameters
name: web-application
description: Containerized web application
owner: platform-team
replicas: 3
resources:
  cpu: "500m"
  memory: "512Mi"

# Generated container structure
web-application/
├── src/
├── Dockerfile
├── .dockerignore
├── k8s/
│   ├── deployment.yaml
│   ├── service.yaml
│   └── ingress.yaml
├── docker-compose.yml
└── skaffold.yaml
\`\`\`

Container features:
- Multi-stage Docker build
- Security scanning
- Kubernetes manifests
- Health checks
- Resource limits
- Horizontal pod autoscaling
`;
  }

  private generateCloudUsageExample(spec: TemplateSpec): string {
    return `## Cloud-Native Application Example

Creating a cloud-native application with AWS services:

\`\`\`yaml
# Template parameters
name: serverless-api
description: Serverless API using AWS Lambda
owner: cloud-team
runtime: nodejs18.x
memory: 256
timeout: 30

# Generated cloud structure
serverless-api/
├── src/
│   └── handlers/
├── infrastructure/
│   ├── cloudformation.yaml
│   └── terraform/
├── tests/
└── deployment/
    ├── buildspec.yml
    └── pipeline.yaml
\`\`\`

Cloud features:
- AWS Lambda functions
- API Gateway integration
- DynamoDB tables
- CloudWatch monitoring
- IAM roles and policies
- CI/CD pipeline
- Cost optimization
`;
  }

  private generateAdvancedUsageExample(spec: TemplateSpec): string {
    return `## Advanced Governance Example

Creating a high-maturity template with governance and policy enforcement:

\`\`\`yaml
# Template parameters
name: enterprise-service
description: Enterprise-grade service with full governance
owner: platform-team
maturity: L4_GOVERNANCE
compliance: SOX
security_level: high

# Generated governance structure
enterprise-service/
├── src/
├── governance/
│   ├── policies/
│   ├── compliance/
│   └── security/
├── monitoring/
│   ├── dashboards/
│   └── alerts/
├── docs/
│   ├── architecture/
│   ├── security/
│   └── compliance/
└── automation/
    ├── policy-checks/
    └── compliance-reports/
\`\`\`

Governance features:
- Automated policy enforcement
- Compliance reporting
- Security scanning
- Architecture decision records
- Risk assessment
- Audit trails
`;
  }

  // Additional helper methods for generating various documentation sections
  private detectTemplateType(spec: TemplateSpec): string {
    const tags = spec.metadata.tags;

    if (tags.includes('api') || tags.includes('service')) return 'API Service';
    if (tags.includes('frontend') || tags.includes('ui'))
      return 'Frontend Application';
    if (tags.includes('data') || tags.includes('pipeline'))
      return 'Data Pipeline';
    if (tags.includes('library') || tags.includes('package'))
      return 'Library Package';
    if (tags.includes('infrastructure')) return 'Infrastructure';

    return 'Application';
  }

  private generateStructurePreview(spec: TemplateSpec): string {
    const templateType = this.detectTemplateType(spec);

    switch (templateType) {
      case 'API Service':
        return `my-api-service/
├── src/
│   ├── controllers/
│   ├── models/
│   ├── routes/
│   └── middleware/
├── tests/
├── docs/
├── Dockerfile
└── package.json`;

      case 'Frontend Application':
        return `my-frontend-app/
├── src/
│   ├── components/
│   ├── pages/
│   ├── styles/
│   └── utils/
├── public/
├── tests/
└── package.json`;

      case 'Data Pipeline':
        return `my-data-pipeline/
├── src/
│   ├── extractors/
│   ├── transformers/
│   └── loaders/
├── config/
├── tests/
└── requirements.txt`;

      default:
        return `my-component/
├── src/
├── tests/
├── docs/
└── README.md`;
    }
  }

  private generateDevelopmentGuidelines(spec: TemplateSpec): string {
    return `### Code Style
- Follow the established coding standards for your language
- Use meaningful variable and function names
- Write comprehensive tests for new functionality
- Document public APIs and complex logic

### Git Workflow
- Create feature branches from main/master
- Write clear, descriptive commit messages
- Submit pull requests for code review
- Ensure all tests pass before merging

### Testing
- Write unit tests for business logic
- Include integration tests for API endpoints
- Maintain test coverage above 80%
- Run tests locally before committing

### Documentation
- Update README for significant changes
- Document API changes in OpenAPI spec
- Keep architecture decisions recorded
- Update deployment guides as needed`;
  }

  private generateTroubleshooting(spec: TemplateSpec): string {
    return `### Common Issues

**Template Creation Fails**
- Verify all required parameters are provided
- Check that the template name doesn't conflict with existing components
- Ensure you have necessary permissions

**Build Failures**
- Check that all dependencies are properly specified
- Verify the build configuration matches your environment
- Review the build logs for specific error messages

**Deployment Issues**
- Confirm infrastructure prerequisites are met
- Verify environment-specific configuration
- Check resource quotas and limits

**Permission Errors**
- Ensure your account has the necessary permissions
- Verify service account configurations
- Check RBAC policies if using Kubernetes`;
  }

  private generateContributingSection(spec: TemplateSpec): string {
    return `We welcome contributions to improve this template! Please:

1. **Fork the repository** and create a feature branch
2. **Make your changes** following the coding standards
3. **Add tests** for new functionality
4. **Update documentation** as needed
5. **Submit a pull request** with a clear description

### Template Improvements
- Add new parameters or configuration options
- Improve generated code quality
- Enhance documentation and examples
- Fix bugs or security issues

### Review Process
All contributions go through a review process to ensure:
- Code quality and consistency
- Security best practices
- Compatibility with existing systems
- Proper documentation`;
  }

  // Additional helper methods for TechDocs generation
  private generateArchitectureSection(spec: TemplateSpec): string {
    const templateType = this.detectTemplateType(spec);

    return `The ${templateType} template follows a layered architecture pattern:

- **Presentation Layer**: User interface and API endpoints
- **Business Logic Layer**: Core application logic and rules
- **Data Access Layer**: Database and external service integration
- **Infrastructure Layer**: Deployment and operational concerns

This separation ensures maintainability, testability, and scalability.`;
  }

  private generateComponentOverview(spec: TemplateSpec): string {
    return `### Core Components

- **Application Core**: Main business logic and domain models
- **API Layer**: REST endpoints and request/response handling
- **Data Layer**: Database models and data access patterns
- **Configuration**: Environment-specific settings and secrets
- **Testing**: Unit tests, integration tests, and test utilities
- **Documentation**: API docs, architecture guides, and runbooks`;
  }

  private generateImplementationDetails(spec: TemplateSpec): string {
    return `### Key Implementation Decisions

- **Framework Choice**: Selected based on team expertise and requirements
- **Database Integration**: Configured for scalability and performance
- **Security Implementation**: Following organizational security standards
- **Monitoring Setup**: Comprehensive observability and alerting
- **Deployment Strategy**: Automated CI/CD with proper testing gates`;
  }

  private generateParameterSchema(spec: TemplateSpec): string {
    return `The template parameters follow a JSON Schema specification:

\`\`\`json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Component name"
    },
    "description": {
      "type": "string", 
      "description": "Component description"
    },
    "owner": {
      "type": "string",
      "description": "Team or individual owner"
    }
  },
  "required": ["name", "description", "owner"]
}
\`\`\``;
  }

  private generateStepImplementation(spec: TemplateSpec): string {
    return `### Template Steps

Each step in the template execution performs specific actions:

1. **Validation**: Verify parameters and prerequisites
2. **Scaffolding**: Generate project structure and files
3. **Configuration**: Apply environment-specific settings
4. **Integration**: Set up CI/CD and monitoring
5. **Documentation**: Generate comprehensive docs
6. **Finalization**: Commit to repository and trigger deployment`;
  }

  private generateValidationFramework(spec: TemplateSpec): string {
    return `### Validation Rules

The template includes comprehensive validation:

- **Security Validation**: Checks for security best practices
- **Code Quality**: Enforces coding standards and patterns
- **Configuration Validation**: Verifies environment settings
- **Dependency Scanning**: Checks for vulnerable dependencies
- **Compliance Checks**: Ensures regulatory compliance`;
  }

  private generateSecurityConsiderations(spec: TemplateSpec): string {
    return `### Security Best Practices

- **Authentication**: Implement proper authentication mechanisms
- **Authorization**: Use role-based access control (RBAC)
- **Data Protection**: Encrypt sensitive data at rest and in transit
- **Input Validation**: Sanitize and validate all user inputs
- **Dependency Management**: Keep dependencies updated and secure
- **Secrets Management**: Use proper secret management solutions`;
  }

  private generatePerformanceGuidelines(spec: TemplateSpec): string {
    return `### Performance Optimization

- **Caching**: Implement appropriate caching strategies
- **Database Optimization**: Use proper indexing and query optimization
- **Resource Management**: Set appropriate resource limits
- **Monitoring**: Track key performance metrics
- **Scaling**: Design for horizontal scaling
- **Load Testing**: Regular performance testing`;
  }

  private generateMonitoringSection(spec: TemplateSpec): string {
    return `### Monitoring and Observability

- **Metrics**: Application and infrastructure metrics
- **Logging**: Structured logging with appropriate levels
- **Tracing**: Distributed tracing for complex workflows
- **Alerting**: Proactive alerting on key indicators
- **Dashboards**: Visual monitoring dashboards
- **Health Checks**: Comprehensive health check endpoints`;
  }

  private generateDeploymentStrategy(spec: TemplateSpec): string {
    return `### Deployment Approach

- **Blue-Green Deployment**: Zero-downtime deployments
- **Rolling Updates**: Gradual rollout of changes
- **Canary Releases**: Test changes with subset of traffic
- **Rollback Strategy**: Quick rollback capabilities
- **Environment Promotion**: Staged deployment pipeline
- **Infrastructure as Code**: Automated infrastructure management`;
  }

  private generateMaintenanceSection(spec: TemplateSpec): string {
    return `### Maintenance Procedures

- **Regular Updates**: Keep dependencies and base images updated
- **Security Patches**: Apply security updates promptly
- **Performance Monitoring**: Regular performance reviews
- **Capacity Planning**: Monitor and plan for growth
- **Backup Procedures**: Regular backup and recovery testing
- **Documentation Updates**: Keep documentation current`;
  }

  private generateApiReference(spec: TemplateSpec): string {
    if (!this.isApiTemplate(spec)) {
      return 'This template does not generate API endpoints.';
    }

    return `### API Endpoints

The generated API includes the following endpoints:

- \`GET /health\` - Health check endpoint
- \`GET /metrics\` - Prometheus metrics
- \`GET /api/v1/resources\` - List resources
- \`POST /api/v1/resources\` - Create resource
- \`GET /api/v1/resources/:id\` - Get resource by ID
- \`PUT /api/v1/resources/:id\` - Update resource
- \`DELETE /api/v1/resources/:id\` - Delete resource

See the OpenAPI specification for detailed request/response schemas.`;
  }

  private generateConfigurationReference(spec: TemplateSpec): string {
    return `### Configuration Options

The application supports the following configuration:

- **Environment Variables**: Runtime configuration
- **Config Files**: YAML/JSON configuration files
- **Secrets**: Sensitive configuration via secret management
- **Feature Flags**: Runtime feature toggles
- **Database Configuration**: Connection strings and pool settings
- **Logging Configuration**: Log levels and output formats`;
  }

  private generateDetailedTroubleshooting(spec: TemplateSpec): string {
    return `### Troubleshooting Guide

#### Application Won't Start
1. Check environment variables are set correctly
2. Verify database connectivity
3. Review application logs for errors
4. Confirm all dependencies are installed

#### Performance Issues
1. Check resource utilization (CPU, memory)
2. Review database query performance
3. Analyze application metrics
4. Check for memory leaks

#### Deployment Failures
1. Verify deployment configuration
2. Check resource quotas and limits
3. Review CI/CD pipeline logs
4. Confirm infrastructure prerequisites

#### Database Connection Issues
1. Verify connection string format
2. Check database server availability
3. Confirm authentication credentials
4. Review network connectivity`;
  }

  private generateChangeLog(spec: TemplateSpec): string {
    return `### Change Log

#### Version 1.0.0
- Initial template release
- Basic project structure
- Core functionality implementation
- Documentation and testing setup

#### Future Versions
- Additional features based on feedback
- Performance improvements
- Security enhancements
- Extended documentation`;
  }

  // API-specific documentation methods
  private generateApiOverview(spec: TemplateSpec): string {
    return `- **Protocol**: REST API over HTTPS
- **Authentication**: JWT-based authentication
- **Content Type**: JSON request/response format
- **Versioning**: URL-based versioning (v1, v2, etc.)
- **Rate Limiting**: Configurable rate limits per endpoint
- **Documentation**: OpenAPI 3.0 specification included`;
  }

  private generateEndpointsDocumentation(spec: TemplateSpec): string {
    return `### Core Endpoints

#### Health Check
- **GET** \`/health\`
- **Description**: Service health status
- **Response**: \`200 OK\` with health information

#### Metrics
- **GET** \`/metrics\`
- **Description**: Prometheus metrics endpoint
- **Response**: Metrics in Prometheus format

#### Resource Management
- **GET** \`/api/v1/resources\`
- **Description**: List all resources
- **Parameters**: \`limit\`, \`offset\`, \`filter\`
- **Response**: Paginated list of resources

- **POST** \`/api/v1/resources\`
- **Description**: Create new resource
- **Body**: Resource object
- **Response**: Created resource with ID`;
  }

  private generateAuthenticationDocs(spec: TemplateSpec): string {
    return `### Authentication

The API uses JWT (JSON Web Token) authentication:

1. **Login**: POST to \`/auth/login\` with credentials
2. **Token**: Receive JWT token in response
3. **Authorization**: Include token in \`Authorization: Bearer <token>\` header
4. **Refresh**: Use refresh token to get new access token

#### Example
\`\`\`bash
# Login
curl -X POST /auth/login \\
  -H "Content-Type: application/json" \\
  -d '{"username": "user", "password": "pass"}'

# Use token
curl -X GET /api/v1/resources \\
  -H "Authorization: Bearer <jwt-token>"
\`\`\``;
  }

  private generateRequestResponseDocs(spec: TemplateSpec): string {
    return `### Request/Response Format

#### Request Format
- **Content-Type**: \`application/json\`
- **Encoding**: UTF-8
- **Structure**: JSON objects with camelCase properties

#### Response Format
- **Content-Type**: \`application/json\`
- **Status Codes**: Standard HTTP status codes
- **Error Format**: Consistent error response structure

#### Example Response
\`\`\`json
{
  "data": {
    "id": "123",
    "name": "Example Resource",
    "createdAt": "2023-01-01T00:00:00Z"
  },
  "meta": {
    "timestamp": "2023-01-01T00:00:00Z",
    "version": "1.0.0"
  }
}
\`\`\``;
  }

  private generateErrorHandlingDocs(spec: TemplateSpec): string {
    return `### Error Handling

#### Error Response Format
\`\`\`json
{
  "error": {
    "code": "VALIDATION_ERROR",
    "message": "Invalid input data",
    "details": [
      {
        "field": "name",
        "message": "Name is required"
      }
    ]
  },
  "meta": {
    "timestamp": "2023-01-01T00:00:00Z",
    "requestId": "req-123"
  }
}
\`\`\`

#### Common Error Codes
- \`400\` - Bad Request: Invalid input data
- \`401\` - Unauthorized: Authentication required
- \`403\` - Forbidden: Insufficient permissions
- \`404\` - Not Found: Resource not found
- \`429\` - Too Many Requests: Rate limit exceeded
- \`500\` - Internal Server Error: Server error`;
  }

  private generateRateLimitingDocs(spec: TemplateSpec): string {
    return `### Rate Limiting

The API implements rate limiting to ensure fair usage:

- **Default Limit**: 1000 requests per hour per API key
- **Headers**: Rate limit information in response headers
- **Exceeded**: \`429 Too Many Requests\` when limit exceeded

#### Rate Limit Headers
\`\`\`
X-RateLimit-Limit: 1000
X-RateLimit-Remaining: 999
X-RateLimit-Reset: 1640995200
\`\`\``;
  }

  private generateOpenApiDocs(spec: TemplateSpec): string {
    return `### OpenAPI Specification

The complete API specification is available in OpenAPI 3.0 format:

- **File**: \`openapi.yaml\` in the project root
- **Interactive Docs**: Available at \`/api-docs\` endpoint
- **Schema Validation**: Automatic request/response validation
- **Code Generation**: Use spec to generate client SDKs

#### Accessing the Specification
- **YAML**: \`GET /openapi.yaml\`
- **JSON**: \`GET /openapi.json\`
- **UI**: \`GET /api-docs\` (Swagger UI)`;
  }

  private generateSdkDocs(spec: TemplateSpec): string {
    return `### SDK and Client Libraries

Client libraries can be generated from the OpenAPI specification:

#### JavaScript/TypeScript
\`\`\`bash
npm install @openapitools/openapi-generator-cli
openapi-generator-cli generate -i openapi.yaml -g typescript-axios -o ./client
\`\`\`

#### Python
\`\`\`bash
pip install openapi-generator-cli
openapi-generator-cli generate -i openapi.yaml -g python -o ./client
\`\`\`

#### Java
\`\`\`bash
openapi-generator-cli generate -i openapi.yaml -g java -o ./client
\`\`\``;
  }

  private generateApiTestingDocs(spec: TemplateSpec): string {
    return `### API Testing

#### Unit Tests
- Test individual endpoint handlers
- Mock external dependencies
- Validate request/response schemas

#### Integration Tests
- Test complete API workflows
- Use test database
- Validate business logic

#### Load Testing
- Performance testing with realistic load
- Identify bottlenecks and limits
- Validate scaling behavior

#### Example Test
\`\`\`javascript
describe('GET /api/v1/resources', () => {
  it('should return list of resources', async () => {
    const response = await request(app)
      .get('/api/v1/resources')
      .expect(200);
    
    expect(response.body.data).toBeInstanceOf(Array);
  });
});
\`\`\``;
  }

  // Helper methods for template detection
  private isApiTemplate(spec: TemplateSpec): boolean {
    const tags = spec.metadata.tags.map((tag) => tag.toLowerCase());
    const description = spec.metadata.description.toLowerCase();

    return (
      tags.some((tag) =>
        ['api', 'rest', 'graphql', 'service', 'backend'].includes(tag)
      ) ||
      description.includes('api') ||
      description.includes('service')
    );
  }

  private isDataTemplate(spec: TemplateSpec): boolean {
    const tags = spec.metadata.tags.map((tag) => tag.toLowerCase());
    const description = spec.metadata.description.toLowerCase();

    return (
      tags.some((tag) =>
        ['data', 'pipeline', 'etl', 'analytics', 'database'].includes(tag)
      ) ||
      description.includes('data') ||
      description.includes('pipeline')
    );
  }

  private isContainerTemplate(spec: TemplateSpec): boolean {
    const tags = spec.metadata.tags.map((tag) => tag.toLowerCase());
    const description = spec.metadata.description.toLowerCase();

    return (
      tags.some((tag) =>
        ['docker', 'container', 'kubernetes', 'k8s'].includes(tag)
      ) ||
      description.includes('docker') ||
      description.includes('container')
    );
  }

  private isCloudTemplate(spec: TemplateSpec): boolean {
    const tags = spec.metadata.tags.map((tag) => tag.toLowerCase());
    const description = spec.metadata.description.toLowerCase();

    return (
      tags.some((tag) =>
        ['aws', 'azure', 'gcp', 'cloud', 'serverless', 'lambda'].includes(tag)
      ) ||
      description.includes('cloud') ||
      description.includes('aws')
    );
  }

  private extractMaturityLevel(spec: TemplateSpec): CapabilityMaturity {
    const tags = spec.metadata.tags.map((tag) => tag.toLowerCase());

    if (tags.includes('l5') || tags.includes('intent-driven')) {
      return CapabilityMaturity.L5_INTENT_DRIVEN;
    }
    if (tags.includes('l4') || tags.includes('governance')) {
      return CapabilityMaturity.L4_GOVERNANCE;
    }
    if (tags.includes('l3') || tags.includes('operations')) {
      return CapabilityMaturity.L3_OPERATIONS;
    }
    if (tags.includes('l2') || tags.includes('deployment')) {
      return CapabilityMaturity.L2_DEPLOYMENT;
    }

    return CapabilityMaturity.L1_GENERATION;
  }

  private getStepDescription(action: string): string {
    const stepDescriptions: Record<string, string> = {
      'fetch:template': 'Fetch the template files from the repository',
      'publish:github':
        'Create a new GitHub repository with the generated code',
      'register:catalog': 'Register the component in the Backstage catalog',
      'publish:gitlab':
        'Create a new GitLab repository with the generated code',
      'fetch:plain': 'Fetch plain files without templating',
      'debug:log': 'Log debug information during template execution',
    };

    return stepDescriptions[action] || `Execute ${action} action`;
  }
}
