apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl | parseRepoUrl | pick("owner") }}/${{ values.repoUrl | parseRepoUrl | pick("repo") }}
spec:
  type: service
  lifecycle: experimental
  owner: frontend-team